# -*- coding: utf-8 -*-
"""Colon5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVFD5WMHp3lbLsuVo2E99EV1HGejbTKR

# Colon5 — CRC Grading: Federated vs Centralized Learning on CRC-HGD-v2

**Publication-ready pipeline for Q1 conference submission.**

## Experimental Design
| Experiment | Description | Hyperparameters |
|---|---|---|
| **Centralized** | Single-node training baseline | lr=3e-4, 20 epochs, cosine LR |
| **FL-FedProx IID** | Federated learning, IID partition | 4 clients, 15 rounds, mu=0.001, le=2 |

## Magnification Branches
- `with_4x`: all magnifications (4×/10×/20×/40×)
- `without_4x`: clinical magnifications only (10×/20×/40×)

## Dataset: CRC-HGD-v2
- 1899 histopathology images across 3 colorectal cancer grades
- Grade I (Well Differentiated), Grade II (Moderately Differentiated), Grade III (Poorly Differentiated)

## Model: SharedGatedDualScale (MobileNetV3-Large)
- Dual-scale input: context (224×224) + detail (320×320)
- Shared encoder with learned gated fusion
- ~4.5M trainable parameters
"""

# ============================================================
# Cell 1 — Imports & Setup
# ============================================================
import os, sys, json, random, copy, warnings
from pathlib import Path
from dataclasses import dataclass, asdict

import numpy as np
import pandas as pd
import cv2
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from matplotlib.gridspec import GridSpec

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

import timm
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (
    confusion_matrix, classification_report,
    accuracy_score, f1_score, roc_auc_score
)

try:
    import albumentations as A
    from albumentations.pytorch import ToTensorV2
except ImportError as e:
    raise ImportError("Install albumentations: pip install albumentations") from e

warnings.filterwarnings('ignore')

# ----------------------------------------------------------
# Paths
# ----------------------------------------------------------
PROJECT_ROOT = Path("/Users/shorna/Projects/Rafiul Project 1/colon")
DATA_ROOT    = PROJECT_ROOT / "datasets" / "CRC-HGD-v2"
OUT_BASE     = PROJECT_ROOT / "CRC_OUTPUT" / "colon5_publication"
OUT_BASE.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------
# Device
# ----------------------------------------------------------
if torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
elif torch.cuda.is_available():
    DEVICE = torch.device("cuda")
else:
    DEVICE = torch.device("cpu")

USE_AMP = DEVICE.type == "cuda"
print(f"Device: {DEVICE}  |  AMP: {USE_AMP}")

# ----------------------------------------------------------
# Constants
# ----------------------------------------------------------
GRADE_DIR_MAP = {
    "CRC_Grade__1__Well_Diff":   "Grade_I",
    "CRC_Grade__2__Mod_Diff":    "Grade_II",
    "CRC_Grade__3__Poorly_Diff": "Grade_III",
}
CLASS_NAMES  = ["Grade_I", "Grade_II", "Grade_III"]
LABEL_MAP    = {c: i for i, c in enumerate(CLASS_NAMES)}
IMAGE_EXTS   = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp", ".webp"}
BACKBONE     = "mobilenetv3_large_100"

# Publication plot style
plt.rcParams.update({
    'font.family':       'DejaVu Sans',
    'font.size':         11,
    'axes.titlesize':    12,
    'axes.labelsize':    11,
    'xtick.labelsize':   10,
    'ytick.labelsize':   10,
    'legend.fontsize':   10,
    'figure.dpi':        150,
    'savefig.dpi':       300,
    'savefig.bbox':      'tight',
})
COLORS = ['#2196F3', '#FF5722', '#4CAF50', '#9C27B0']

# ----------------------------------------------------------
# Reproducibility
# ----------------------------------------------------------
def seed_everything(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

seed_everything(42)
print("Imports and setup complete.")

# ============================================================
# Cell 2 — Configuration
# ============================================================
@dataclass
class CFG:
    # model / data
    num_classes:      int   = 3
    size_context:     int   = 224
    size_detail:      int   = 320
    batch_size:       int   = 16
    num_workers:      int   = 0
    # optimisation
    lr:               float = 3e-4
    weight_decay:     float = 1e-4
    label_smoothing:  float = 0.05
    # centralized — increased epochs + cosine warmup for better convergence
    central_epochs:   int   = 20
    # FL shared — more rounds to converge
    clients:          int   = 4
    rounds:           int   = 15
    server_lr:        float = 1.0
    # FL IID best params
    iid_mu:           float = 0.001
    iid_local_epochs: int   = 2
    # split
    val_frac:         float = 0.15
    test_frac:        float = 0.15
    seed:             int   = 42
    use_amp:          bool  = USE_AMP

CFG_DEFAULT = CFG()
print("Configuration:")
for k, v in asdict(CFG_DEFAULT).items():
    print(f"  {k:22s}: {v}")

# ============================================================
# Cell 3 — Dataset Index Builder
# ============================================================
def build_index(data_root: Path, keep_4x: bool = True) -> pd.DataFrame:
    """Walk CRC-HGD-v2 directory and return a DataFrame of all images.
    Structure: grade_dir / mag_dir / image_file  (flat, no specimen subdir)
    """
    records = []
    for grade_dir, grade_label in GRADE_DIR_MAP.items():
        grade_path = data_root / grade_dir
        if not grade_path.exists():
            print(f"  WARNING: missing {grade_path}")
            continue
        for mag_dir in sorted(grade_path.iterdir()):
            if not mag_dir.is_dir():
                continue
            mag = mag_dir.name                    # e.g. "40x", "10x"
            mag_num = mag.rstrip('Xx').lstrip('0') or '0'
            if not keep_4x and mag_num == '4':
                continue
            for img_file in sorted(mag_dir.iterdir()):
                if img_file.suffix.lower() in IMAGE_EXTS:
                    parts = img_file.stem.split('_')
                    specimen_id = parts[3] if len(parts) > 3 else img_file.stem
                    records.append({
                        "image_path":    str(img_file),
                        "grade":         grade_label,
                        "magnification": mag,
                        "specimen_id":   specimen_id,
                    })
    df = pd.DataFrame(records)
    print(f"  Total images: {len(df)}")
    if df.empty:
        print("  WARNING: no images found — check DATA_ROOT")
        return df
    print(df['grade'].value_counts().to_string())
    print(df['magnification'].value_counts().to_string())
    return df


def split_by_image_stratified(df: pd.DataFrame, cfg: CFG):
    """Image-level stratified split into train / val / test."""
    df = df.sample(frac=1, random_state=cfg.seed).reset_index(drop=True)
    df_trainval, df_test = train_test_split(
        df, test_size=cfg.test_frac, stratify=df["grade"], random_state=cfg.seed
    )
    val_rel = cfg.val_frac / (1.0 - cfg.test_frac)
    df_train, df_val = train_test_split(
        df_trainval, test_size=val_rel, stratify=df_trainval["grade"], random_state=cfg.seed
    )
    return {
        "train": df_train.reset_index(drop=True),
        "val":   df_val.reset_index(drop=True),
        "test":  df_test.reset_index(drop=True),
    }

print("Dataset index functions defined.")

# ============================================================
# Cell 4 — EDA: Dataset Statistics & Sample Grid
# ============================================================
def plot_dataset_statistics(out_dir: Path):
    """Publication-quality EDA figures."""
    out_dir.mkdir(parents=True, exist_ok=True)

    # --- gather counts ---
    data = []
    for gd, gl in GRADE_DIR_MAP.items():
        gp = DATA_ROOT / gd
        for mag_dir in sorted(gp.iterdir()):
            if not mag_dir.is_dir(): continue
            imgs = [f for f in mag_dir.iterdir() if f.suffix.lower() in IMAGE_EXTS]
            data.append({'grade': gl, 'magnification': mag_dir.name, 'count': len(imgs)})
    df_counts = pd.DataFrame(data)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # (a) images per grade
    grade_totals = df_counts.groupby('grade')['count'].sum().reindex(CLASS_NAMES)
    bars = axes[0].bar(CLASS_NAMES, grade_totals.values,
                       color=COLORS[:3], edgecolor='white', linewidth=1.2)
    for bar, v in zip(bars, grade_totals.values):
        axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                     str(v), ha='center', va='bottom', fontweight='bold')
    axes[0].set_xlabel('CRC Grade')
    axes[0].set_ylabel('Image Count')
    axes[0].set_title('(a) Images per CRC Grade')
    axes[0].set_ylim(0, grade_totals.max() * 1.15)
    axes[0].spines['top'].set_visible(False)
    axes[0].spines['right'].set_visible(False)

    # (b) stacked bar per magnification
    pivot = df_counts.pivot_table(index='magnification', columns='grade',
                                   values='count', aggfunc='sum', fill_value=0)
    mags = sorted(pivot.index, key=lambda x: int(x.rstrip('xX')))
    pivot = pivot.reindex(mags)
    bottom = np.zeros(len(mags))
    for ci, cn in enumerate(CLASS_NAMES):
        vals = pivot[cn].values if cn in pivot.columns else np.zeros(len(mags))
        axes[1].bar(mags, vals, bottom=bottom, color=COLORS[ci], label=cn,
                    edgecolor='white', linewidth=0.8)
        bottom += vals
    axes[1].set_xlabel('Magnification')
    axes[1].set_ylabel('Image Count')
    axes[1].set_title('(b) Distribution by Magnification & Grade')
    axes[1].legend(loc='upper right')
    axes[1].spines['top'].set_visible(False)
    axes[1].spines['right'].set_visible(False)

    fig.suptitle('CRC-HGD-v2 Dataset Statistics', fontsize=13, fontweight='bold')
    fig.tight_layout()
    fig.savefig(out_dir / 'fig_dataset_statistics.png')
    plt.show()
    print(f"  Saved: fig_dataset_statistics.png")
    plt.close(fig)
    return df_counts


def plot_sample_images(out_dir: Path, n_per_class: int = 3):
    """Grid of representative histopathology patches."""
    out_dir.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(len(CLASS_NAMES), n_per_class,
                              figsize=(n_per_class * 3, len(CLASS_NAMES) * 3))
    for row, (gd, gl) in enumerate(GRADE_DIR_MAP.items()):
        mag_path = DATA_ROOT / gd / '40x'
        imgs = sorted(mag_path.glob('*.jpg'))[:n_per_class] if mag_path.exists() else []
        for col in range(n_per_class):
            ax = axes[row][col]
            if col < len(imgs):
                img = cv2.cvtColor(cv2.imread(str(imgs[col])), cv2.COLOR_BGR2RGB)
                ax.imshow(img)
            else:
                ax.set_facecolor('#f0f0f0')
            ax.axis('off')
            if col == 0:
                ax.set_ylabel(gl.replace('_', ' '), fontsize=11, fontweight='bold')
                ax.yaxis.set_label_coords(-0.08, 0.5)
                ax.set_ylabel(gl.replace('_', ' '), rotation=90, labelpad=5,
                               fontsize=10, fontweight='bold')
            if row == 0:
                ax.set_title(f'Sample {col+1}', fontsize=10)
    fig.suptitle('Representative Histopathology Patches (40×)', fontsize=12, fontweight='bold')
    fig.tight_layout()
    fig.savefig(out_dir / 'fig_sample_patches.png')
    plt.show()
    print(f"  Saved: fig_sample_patches.png")
    plt.close(fig)


eda_dir = OUT_BASE / 'eda'
df_counts = plot_dataset_statistics(eda_dir)
plot_sample_images(eda_dir)

# Print dataset table
print("\nDataset summary table:")
tbl = df_counts.pivot_table(index='grade', columns='magnification',
                             values='count', aggfunc='sum', fill_value=0)
tbl['Total'] = tbl.sum(axis=1)
tbl.loc['Total'] = tbl.sum()
print(tbl.to_string())

# ============================================================
# Cell 5 — Transforms & Dataset
# ============================================================
def make_transforms(size: int, train: bool = True):
    mean = (0.485, 0.456, 0.406)
    std  = (0.229, 0.224, 0.225)
    if train:
        try:
            rrc = A.RandomResizedCrop(size=(size, size), scale=(0.7, 1.0), ratio=(0.85, 1.15))
        except TypeError:
            rrc = A.RandomResizedCrop(height=size, width=size, scale=(0.7, 1.0), ratio=(0.85, 1.15))
        return A.Compose([
            rrc,
            A.HorizontalFlip(p=0.5),
            A.VerticalFlip(p=0.5),
            A.RandomRotate90(p=0.5),
            A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1, p=0.6),
            A.HueSaturationValue(p=0.3),
            A.GaussianBlur(blur_limit=(3, 5), p=0.2),
            A.Normalize(mean=mean, std=std),
            ToTensorV2(),
        ])
    else:
        return A.Compose([
            A.LongestMaxSize(max_size=size),
            A.PadIfNeeded(min_height=size, min_width=size, border_mode=cv2.BORDER_CONSTANT),
            A.CenterCrop(height=size, width=size),
            A.Normalize(mean=mean, std=std),
            ToTensorV2(),
        ])


class CRCDataset(Dataset):
    def __init__(self, df: pd.DataFrame, tf_context, tf_detail):
        self.df = df.reset_index(drop=True).copy()
        self.tf_context = tf_context
        self.tf_detail  = tf_detail

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = cv2.imread(str(row["image_path"]))
        if img is None:
            raise RuntimeError(f"Cannot read: {row['image_path']}")
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        x_c = self.tf_context(image=img)["image"]
        x_d = self.tf_detail(image=img)["image"]
        y   = LABEL_MAP[row["grade"]]
        return (x_c, x_d), y


def make_sample_weights(df: pd.DataFrame):
    y = df["grade"].map(LABEL_MAP).to_numpy()
    counts = np.bincount(y, minlength=len(CLASS_NAMES)).astype(np.float64)
    inv = 1.0 / (counts + 1e-12)
    return torch.as_tensor(inv[y], dtype=torch.double)


def make_loader(df: pd.DataFrame, cfg: CFG, train: bool = True, use_sampler: bool = False):
    tf_c = make_transforms(cfg.size_context, train=train)
    tf_d = make_transforms(cfg.size_detail,  train=train)
    ds = CRCDataset(df, tf_c, tf_d)
    if train and use_sampler:
        weights = make_sample_weights(df)
        sampler = WeightedRandomSampler(weights, num_samples=len(weights), replacement=True)
        return DataLoader(ds, batch_size=cfg.batch_size, sampler=sampler,
                          shuffle=False, num_workers=cfg.num_workers,
                          pin_memory=(DEVICE.type=="cuda"), drop_last=True)
    return DataLoader(ds, batch_size=cfg.batch_size, shuffle=train,
                      num_workers=cfg.num_workers,
                      pin_memory=(DEVICE.type=="cuda"), drop_last=train)

print("Transforms and Dataset defined.")

# ============================================================
# Cell 6 — Model: SharedGatedDualScale (MobileNetV3)
# ============================================================
class SharedGatedDualScale(nn.Module):
    """Shared MobileNetV3 encoder with gated dual-scale feature fusion.

    Architecture:
        context branch (224) ─┐
                               ├─► gate ─► fused ─► head ─► logits
        detail  branch (320) ─┘
    The gate is a 2-layer MLP producing element-wise blend weights.
    """

    def __init__(self, backbone_name: str = BACKBONE, num_classes: int = 3, dropout: float = 0.3):
        super().__init__()
        self.encoder = timm.create_model(backbone_name, pretrained=True,
                                          num_classes=0, global_pool="avg")
        # Probe real output dim — timm num_features can differ from actual output
        with torch.no_grad():
            feat_dim = self.encoder(torch.zeros(1, 3, 224, 224)).shape[1]

        self.gate = nn.Sequential(
            nn.Linear(feat_dim * 2, feat_dim),
            nn.ReLU(inplace=True),
            nn.Linear(feat_dim, feat_dim),
            nn.Sigmoid(),
        )
        self.head = nn.Sequential(
            nn.LayerNorm(feat_dim),
            nn.Dropout(dropout),
            nn.Linear(feat_dim, num_classes),
        )

    def forward(self, x_context, x_detail):
        f_c = self.encoder(x_context)
        f_d = self.encoder(x_detail)
        g   = self.gate(torch.cat([f_c, f_d], dim=1))
        f   = g * f_d + (1.0 - g) * f_c
        return self.head(f)


def build_model(cfg: CFG) -> SharedGatedDualScale:
    return SharedGatedDualScale(BACKBONE, cfg.num_classes).to(DEVICE)


def count_params(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


# Sanity check
_tmp = build_model(CFG_DEFAULT)
print(f"Model: SharedGatedDualScale({BACKBONE})")
print(f"Trainable parameters: {count_params(_tmp):,}")
_x = (torch.zeros(2, 3, 224, 224).to(DEVICE), torch.zeros(2, 3, 320, 320).to(DEVICE))
_out = _tmp(*_x)
print(f"Output shape: {_out.shape}  (expected: [2, 3])")
del _tmp, _x, _out

# ============================================================
# Cell 7 — Loss, Training & Evaluation
# ============================================================
def make_criterion(df: pd.DataFrame, cfg: CFG):
    """Inverse-frequency weighted CrossEntropyLoss with label smoothing."""
    y = df["grade"].map(LABEL_MAP).to_numpy()
    counts = np.bincount(y, minlength=len(CLASS_NAMES)).astype(np.float32)
    w = 1.0 / (counts + 1e-6)
    w = w / w.sum() * len(CLASS_NAMES)
    weight = torch.tensor(w, dtype=torch.float32, device=DEVICE)
    return nn.CrossEntropyLoss(weight=weight, label_smoothing=cfg.label_smoothing)


def train_one_epoch(
    model, loader, optimizer, criterion,
    scaler=None, global_params=None, mu: float = 0.0
):
    model.train()
    total_loss, correct, n = 0.0, 0, 0
    for (x_c, x_d), y in loader:
        x_c, x_d, y = x_c.to(DEVICE), x_d.to(DEVICE), y.to(DEVICE)
        optimizer.zero_grad()
        if scaler is not None:
            with torch.autocast(device_type="cuda"):
                logits = model(x_c, x_d)
                loss   = criterion(logits, y)
                if global_params and mu > 0:
                    prox = sum(
                        ((p - gp.to(DEVICE)) ** 2).sum()
                        for (_, p), gp in zip(model.named_parameters(), global_params)
                        if p.requires_grad
                    )
                    loss = loss + (mu / 2.0) * prox
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            logits = model(x_c, x_d)
            loss   = criterion(logits, y)
            if global_params and mu > 0:
                prox = sum(
                    ((p - gp.to(DEVICE)) ** 2).sum()
                    for (_, p), gp in zip(model.named_parameters(), global_params)
                    if p.requires_grad
                )
                loss = loss + (mu / 2.0) * prox
            loss.backward()
            optimizer.step()
        total_loss += loss.item() * len(y)
        correct    += (logits.argmax(1) == y).sum().item()
        n          += len(y)
    return total_loss / n, correct / n


@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    all_preds, all_labels, all_probs = [], [], []
    for (x_c, x_d), y in loader:
        x_c, x_d = x_c.to(DEVICE), x_d.to(DEVICE)
        logits = model(x_c, x_d)
        probs  = torch.softmax(logits, dim=1).cpu().numpy()
        preds  = logits.argmax(1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(y.numpy())
        all_probs.extend(probs)
    acc = accuracy_score(all_labels, all_preds)
    f1  = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    cm  = confusion_matrix(all_labels, all_preds, labels=list(range(len(CLASS_NAMES))))
    per_class_recall = cm.diagonal() / (cm.sum(axis=1) + 1e-12)
    per_class_prec   = cm.diagonal() / (cm.sum(axis=0) + 1e-12)
    per_class_f1     = 2 * per_class_recall * per_class_prec / (per_class_recall + per_class_prec + 1e-12)
    try:
        auc = roc_auc_score(all_labels, np.array(all_probs), multi_class='ovr', average='macro')
    except Exception:
        auc = float('nan')
    return {
        "acc": acc, "macro_f1": f1, "macro_auc": auc,
        "recall_per_class":    per_class_recall.tolist(),
        "precision_per_class": per_class_prec.tolist(),
        "f1_per_class":        per_class_f1.tolist(),
        "cm": cm,
        "preds": all_preds, "labels": all_labels, "probs": np.array(all_probs),
    }

print("Loss, train, eval helpers defined.")

# ============================================================
# Cell 8 — FL Partitioning & Aggregation
# ============================================================
def partition_iid(df: pd.DataFrame, n_clients: int, seed: int = 42):
    """Stratified IID partition — equal class distribution per client."""
    skf = StratifiedKFold(n_splits=n_clients, shuffle=True, random_state=seed)
    clients = {}
    y = df["grade"].map(LABEL_MAP).to_numpy()
    for i, (_, idx) in enumerate(skf.split(df, y)):
        clients[i] = df.iloc[idx].reset_index(drop=True)
    return clients


def get_state_dict_cpu(model: nn.Module):
    return {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}


def load_state_dict_cpu(model: nn.Module, sd: dict):
    model.load_state_dict({k: v.to(DEVICE) for k, v in sd.items()})


def fedavg_aggregate(client_sds: list, client_sizes: list):
    """Weighted FedAvg aggregation by client dataset size."""
    total = sum(client_sizes)
    agg = {}
    for key in client_sds[0]:
        agg[key] = sum(
            client_sds[i][key].float() * (client_sizes[i] / total)
            for i in range(len(client_sds))
        )
    return agg


def blend_sd(global_sd: dict, new_sd: dict, server_lr: float = 1.0):
    if server_lr == 1.0:
        return new_sd
    return {k: global_sd[k] + server_lr * (new_sd[k] - global_sd[k]) for k in global_sd}

print("FL partition and aggregation helpers defined.")

# ============================================================
# Cell 9 Plotting Helpers
# ============================================================
def plot_confusion_matrix(cm, class_names, title, out_path: Path):
    """Normalized + raw count confusion matrix for publication."""
    cm_norm = cm.astype(float) / (cm.sum(axis=1, keepdims=True) + 1e-12)
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    for ax, data, fmt, ttl in zip(
        axes,
        [cm, cm_norm],
        ['d', '.2f'],
        ['Raw Counts', 'Normalized (Recall)'],
    ):
        sns.heatmap(data, annot=True, fmt=fmt, cmap='Blues',
                    xticklabels=class_names, yticklabels=class_names,
                    ax=ax, vmin=0, vmax=(1 if fmt == '.2f' else None),
                    linewidths=0.5, linecolor='lightgray')
        ax.set_xlabel('Predicted Label', fontsize=11)
        ax.set_ylabel('True Label', fontsize=11)
        ax.set_title(f'{title}\n{ttl}', fontsize=11)
        ax.set_xticklabels(ax.get_xticklabels(), rotation=30, ha='right')
        ax.set_yticklabels(ax.get_yticklabels(), rotation=0)
    fig.tight_layout()
    fig.savefig(out_path)
    plt.show()
    plt.close(fig)


def plot_convergence(history: list, title: str, out_path: Path):
    """Dual-panel convergence plot: loss + val metrics."""
    df_h  = pd.DataFrame(history)
    x_col = "round" if "round" in df_h.columns else "epoch"
    xs    = df_h[x_col].values

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    # Loss panel
    if "train_loss" in df_h.columns:
        axes[0].plot(xs, df_h["train_loss"], color=COLORS[0], marker='o',
                     markersize=4, linewidth=2, label='Train Loss')
    axes[0].set_xlabel(x_col.capitalize())
    axes[0].set_ylabel('Loss')
    axes[0].set_title(f'{title}\nTraining Loss')
    axes[0].legend()
    axes[0].spines['top'].set_visible(False)
    axes[0].spines['right'].set_visible(False)

    # Metrics panel
    for col, color, label in [
        ('val_acc',  COLORS[1], 'Val Accuracy'),
        ('val_f1',   COLORS[2], 'Val Macro-F1'),
        ('train_acc', COLORS[3], 'Train Accuracy'),
    ]:
        if col in df_h.columns:
            axes[1].plot(xs, df_h[col], color=color, marker='o',
                         markersize=4, linewidth=2, label=label)
    axes[1].set_xlabel(x_col.capitalize())
    axes[1].set_ylabel('Score')
    axes[1].set_title(f'{title}\nValidation Metrics')
    axes[1].set_ylim(0, 1.05)
    axes[1].legend()
    axes[1].spines['top'].set_visible(False)
    axes[1].spines['right'].set_visible(False)

    fig.tight_layout()
    fig.savefig(out_path)
    plt.show()
    plt.close(fig)


def plot_client_distribution(client_dfs: dict, title: str, out_path: Path):
    """Stacked bar chart of class distribution per FL client."""
    n_clients = len(client_dfs)
    fig, ax = plt.subplots(figsize=(max(8, n_clients * 2), 4))
    x = np.arange(n_clients)
    bottom = np.zeros(n_clients)
    for ci, cn in enumerate(CLASS_NAMES):
        vals = np.array([
            (cdf["grade"] == cn).sum()
            for cdf in client_dfs.values()
        ])
        ax.bar(x, vals, bottom=bottom, color=COLORS[ci], label=cn,
               edgecolor='white', linewidth=0.8)
        bottom += vals
    ax.set_xticks(x)
    ax.set_xticklabels([f'Client {i}' for i in range(n_clients)])
    ax.set_ylabel('Image Count')
    ax.set_title(title)
    ax.legend(loc='upper right')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    fig.tight_layout()
    fig.savefig(out_path)
    plt.show()
    plt.close(fig)


def save_metrics(metrics: dict, out_path: Path):
    row = {
        "acc":       round(metrics["acc"],       4),
        "macro_f1":  round(metrics["macro_f1"],  4),
        "macro_auc": round(metrics["macro_auc"], 4),
    }
    for i, cn in enumerate(CLASS_NAMES):
        row[f"recall_{cn}"]    = round(metrics["recall_per_class"][i],    4)
        row[f"precision_{cn}"] = round(metrics["precision_per_class"][i], 4)
        row[f"f1_{cn}"]        = round(metrics["f1_per_class"][i],        4)
    pd.DataFrame([row]).to_csv(out_path, index=False)

print("Plotting helpers defined.")

# ============================================================
# Cell 10 — Centralized Training Runner
# ============================================================
def run_centralized(splits, cfg: CFG, out_dir: Path, branch_name: str):
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"\n{'='*60}")
    print(f"[Centralized] {branch_name}  lr={cfg.lr}  epochs={cfg.central_epochs}")
    print(f"{'='*60}")

    train_loader = make_loader(splits["train"], cfg, train=True,  use_sampler=True)
    val_loader   = make_loader(splits["val"],   cfg, train=False)
    test_loader  = make_loader(splits["test"],  cfg, train=False)

    model     = build_model(cfg)
    criterion = make_criterion(splits["train"], cfg)
    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
    # Cosine annealing with warm restarts for better convergence
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
        optimizer, T_0=10, T_mult=1, eta_min=1e-6
    )
    scaler = torch.cuda.amp.GradScaler() if cfg.use_amp else None

    best_val_f1, best_sd, history = -1.0, None, []
    patience_counter, patience_limit = 0, 7   # early stopping

    for epoch in range(1, cfg.central_epochs + 1):
        t_loss, t_acc = train_one_epoch(model, train_loader, optimizer, criterion, scaler)
        v_metrics     = evaluate(model, val_loader)
        scheduler.step()

        row = {
            "epoch":      epoch,
            "train_loss": round(t_loss,                   4),
            "train_acc":  round(t_acc,                    4),
            "val_acc":    round(v_metrics["acc"],         4),
            "val_f1":     round(v_metrics["macro_f1"],    4),
            "val_auc":    round(v_metrics["macro_auc"],   4),
        }
        history.append(row)
        print(f"  Epoch {epoch:2d}/{cfg.central_epochs}  "
              f"loss={t_loss:.4f}  t_acc={t_acc:.3f}  "
              f"val_acc={v_metrics['acc']:.3f}  val_f1={v_metrics['macro_f1']:.3f}  "
              f"val_auc={v_metrics['macro_auc']:.3f}")

        if v_metrics["macro_f1"] > best_val_f1:
            best_val_f1 = v_metrics["macro_f1"]
            best_sd     = get_state_dict_cpu(model)
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience_limit:
                print(f"  Early stopping at epoch {epoch} (patience={patience_limit})")
                break

    load_state_dict_cpu(model, best_sd)
    test_metrics = evaluate(model, test_loader)

    print(f"\n  [TEST] acc={test_metrics['acc']:.4f}  "
          f"f1={test_metrics['macro_f1']:.4f}  "
          f"auc={test_metrics['macro_auc']:.4f}  "
          f"recalls={[round(r,3) for r in test_metrics['recall_per_class']]}")

    # Save outputs
    hist_df = pd.DataFrame(history)
    hist_df.to_csv(out_dir / "central_history.csv", index=False)
    save_metrics(test_metrics, out_dir / "central_test_metrics.csv")
    torch.save(best_sd, out_dir / "central_best_model.pt")
    plot_confusion_matrix(
        test_metrics["cm"], CLASS_NAMES,
        f"Centralized — {branch_name}",
        out_dir / "central_confusion_matrix.png"
    )
    plot_convergence(history, f"Centralized — {branch_name}",
                     out_dir / "central_convergence.png")
    print(f"  Saved outputs to {out_dir}")
    return test_metrics

print("Centralized runner defined.")

# ============================================================
# Cell 11 — FL-FedProx IID Runner (adaptive rounds)
# ============================================================
def run_fl_iid(
    splits, cfg: CFG, out_dir: Path, branch_name: str,
    fedprox_mu: float = 0.001,
    local_epochs: int = 2,
    max_rounds: int = 15,
    patience: int = 5,
):
    """Federated learning with IID partition and FedProx regularization.
    Runs for up to max_rounds; stops early if val F1 stops improving.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"\n{'='*60}")
    print(f"[FL-IID FedProx] {branch_name}  mu={fedprox_mu}  le={local_epochs}  "
          f"max_rounds={max_rounds}  clients={cfg.clients}")
    print(f"{'='*60}")

    client_dfs = partition_iid(splits["train"], cfg.clients, seed=cfg.seed)
    plot_client_distribution(
        client_dfs,
        f"FL-IID Client Distribution — {branch_name}",
        out_dir / "iid_client_dist.png"
    )
    for cid, cdf in client_dfs.items():
        print(f"  Client {cid}: {len(cdf)} samples | "
              f"{cdf['grade'].value_counts().to_dict()}")

    val_loader  = make_loader(splits["val"],  cfg, train=False)
    test_loader = make_loader(splits["test"], cfg, train=False)

    global_model = build_model(cfg)
    global_sd    = get_state_dict_cpu(global_model)
    best_val_f1, best_sd = -1.0, None
    history = []
    scaler = torch.cuda.amp.GradScaler() if cfg.use_amp else None
    patience_counter = 0

    for rnd in range(1, max_rounds + 1):
        client_sds, client_sizes = [], []

        for cid, cdf in client_dfs.items():
            local_model = build_model(cfg)
            load_state_dict_cpu(local_model, global_sd)
            criterion = make_criterion(cdf, cfg)
            optimizer = torch.optim.AdamW(
                local_model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay
            )
            loader   = make_loader(cdf, cfg, train=True, use_sampler=False)
            g_params = [p.detach().cpu() for p in global_model.parameters() if p.requires_grad]
            for _ in range(local_epochs):
                train_one_epoch(local_model, loader, optimizer, criterion,
                                scaler=scaler, global_params=g_params, mu=fedprox_mu)
            client_sds.append(get_state_dict_cpu(local_model))
            client_sizes.append(len(cdf))
            del local_model

        new_sd    = fedavg_aggregate(client_sds, client_sizes)
        global_sd = blend_sd(global_sd, new_sd, cfg.server_lr)
        load_state_dict_cpu(global_model, global_sd)

        v_metrics = evaluate(global_model, val_loader)
        row = {
            "round":   rnd,
            "val_acc": round(v_metrics["acc"],      4),
            "val_f1":  round(v_metrics["macro_f1"], 4),
            "val_auc": round(v_metrics["macro_auc"], 4),
        }
        history.append(row)
        print(f"  Round {rnd:2d}/{max_rounds}  "
              f"val_acc={v_metrics['acc']:.3f}  val_f1={v_metrics['macro_f1']:.3f}  "
              f"val_auc={v_metrics['macro_auc']:.3f}")

        if v_metrics["macro_f1"] > best_val_f1:
            best_val_f1 = v_metrics["macro_f1"]
            best_sd     = copy.deepcopy(global_sd)
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"  Early stopping at round {rnd} (patience={patience})")
                break

    load_state_dict_cpu(global_model, best_sd)
    test_metrics = evaluate(global_model, test_loader)

    print(f"\n  [TEST] acc={test_metrics['acc']:.4f}  "
          f"f1={test_metrics['macro_f1']:.4f}  "
          f"auc={test_metrics['macro_auc']:.4f}  "
          f"recalls={[round(r,3) for r in test_metrics['recall_per_class']]}")

    pd.DataFrame(history).to_csv(out_dir / "iid_history.csv", index=False)
    save_metrics(test_metrics, out_dir / "iid_test_metrics.csv")
    torch.save(best_sd, out_dir / "iid_best_model.pt")
    plot_confusion_matrix(
        test_metrics["cm"], CLASS_NAMES,
        f"FL-IID FedProx — {branch_name}",
        out_dir / "iid_confusion_matrix.png"
    )
    plot_convergence(history, f"FL-IID FedProx — {branch_name}",
                     out_dir / "iid_convergence.png")
    print(f"  Saved outputs to {out_dir}")
    return test_metrics

print("FL-IID runner defined.")

# ============================================================
# Cell 12 — Main Loop: Both Branches × 2 Experiments
# ============================================================
cfg         = CFG()
all_results = []
all_splits  = {}   # store splits per branch for later figures

for keep_4x in [True, False]:
    branch_name = "with_4x" if keep_4x else "without_4x"
    out_dir     = OUT_BASE / branch_name
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'#'*60}")
    print(f"# BRANCH: {branch_name}")
    print(f"{'#'*60}")

    # Build index & stratified split
    print("Building dataset index...")
    df_all = build_index(DATA_ROOT, keep_4x=keep_4x)
    splits = split_by_image_stratified(df_all, cfg)
    all_splits[branch_name] = splits
    print(f"  train={len(splits['train'])}  val={len(splits['val'])}  test={len(splits['test'])}")

    splits["train"].to_csv(out_dir / "train_split.csv", index=False)
    splits["val"].to_csv(out_dir / "val_split.csv",     index=False)
    splits["test"].to_csv(out_dir / "test_split.csv",   index=False)

    # ── Experiment 1: Centralized ──────────────────────────
    central_metrics = run_centralized(splits, cfg, out_dir / "centralized", branch_name)
    all_results.append({
        "Branch":       branch_name,
        "Method":       "Centralized",
        "Rounds/Epochs": cfg.central_epochs,
        "LR":           cfg.lr,
        "mu":           "-",
        "Acc":          round(central_metrics["acc"],               4),
        "Macro-F1":     round(central_metrics["macro_f1"],          4),
        "Macro-AUC":    round(central_metrics["macro_auc"],         4),
        "Recall-GI":    round(central_metrics["recall_per_class"][0], 4),
        "Recall-GII":   round(central_metrics["recall_per_class"][1], 4),
        "Recall-GIII":  round(central_metrics["recall_per_class"][2], 4),
        "F1-GI":        round(central_metrics["f1_per_class"][0],   4),
        "F1-GII":       round(central_metrics["f1_per_class"][1],   4),
        "F1-GIII":      round(central_metrics["f1_per_class"][2],   4),
    })

    # ── Experiment 2: FL-IID FedProx ──────────────────────
    iid_metrics = run_fl_iid(
        splits, cfg,
        out_dir       = out_dir / "fl_iid",
        branch_name   = branch_name,
        fedprox_mu    = cfg.iid_mu,
        local_epochs  = cfg.iid_local_epochs,
        max_rounds    = cfg.rounds,
    )
    all_results.append({
        "Branch":       branch_name,
        "Method":       "FL-IID FedProx",
        "Rounds/Epochs": cfg.rounds,
        "LR":           cfg.lr,
        "mu":           cfg.iid_mu,
        "Acc":          round(iid_metrics["acc"],               4),
        "Macro-F1":     round(iid_metrics["macro_f1"],          4),
        "Macro-AUC":    round(iid_metrics["macro_auc"],         4),
        "Recall-GI":    round(iid_metrics["recall_per_class"][0], 4),
        "Recall-GII":   round(iid_metrics["recall_per_class"][1], 4),
        "Recall-GIII":  round(iid_metrics["recall_per_class"][2], 4),
        "F1-GI":        round(iid_metrics["f1_per_class"][0],   4),
        "F1-GII":       round(iid_metrics["f1_per_class"][1],   4),
        "F1-GIII":      round(iid_metrics["f1_per_class"][2],   4),
    })

    print(f"\n  Branch {branch_name} complete.")

print("\n" + "="*60)
print("ALL EXPERIMENTS COMPLETE")
print("="*60)

# ============================================================
# Cell — FL-Dirichlet Only: with_4x and without_4x
# ============================================================

def partition_dirichlet_fixed(df, n_clients, alpha=1.0, min_per_class=10,
                               min_size=50, seed=42, max_tries=200):
    rng = np.random.default_rng(seed)
    y = df["grade"].map(LABEL_MAP).to_numpy()
    n_classes = len(CLASS_NAMES)

    for attempt in range(max_tries):
        idx_by_class = [np.where(y == c)[0] for c in range(n_classes)]
        client_idx = [[] for _ in range(n_clients)]
        for c_idx in idx_by_class:
            rng.shuffle(c_idx)
            props = rng.dirichlet([alpha] * n_clients)
            splits = (np.cumsum(props) * len(c_idx)).astype(int)
            splits[-1] = len(c_idx)
            prev = 0
            for cli, end in enumerate(splits):
                client_idx[cli].extend(c_idx[prev:end].tolist())
                prev = end

        ok = True
        for ci in client_idx:
            if len(ci) < min_size:
                ok = False; break
            cdf_y = y[ci]
            for c in range(n_classes):
                if (cdf_y == c).sum() < min_per_class:
                    ok = False; break
            if not ok:
                break
        if ok:
            print(f"  Partition found on attempt {attempt+1}")
            break
    else:
        print(f"  WARNING: could not satisfy constraints after {max_tries} tries — using last attempt")

    return {i: df.iloc[ci].reset_index(drop=True) for i, ci in enumerate(client_idx)}


def run_fl_dirichlet_fixed(splits, cfg, out_dir, branch_name,
                            alpha=1.0, mu=0.1, local_epochs=2, rounds=20):
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"\n{'='*60}")
    print(f"[FL-DIRICHLET-FIXED] {branch_name}  alpha={alpha}  mu={mu}  "
          f"le={local_epochs}  rounds={rounds}  clients={cfg.clients}")
    print(f"{'='*60}")

    client_dfs = partition_dirichlet_fixed(
        splits["train"], cfg.clients,
        alpha=alpha, min_per_class=10, min_size=50, seed=cfg.seed
    )

    plot_client_distribution(
        client_dfs,
        f"FL-Dirichlet Client Distribution — {branch_name}",
        out_dir / "dirichlet_client_dist.png"
    )
    for cid, cdf in client_dfs.items():
        print(f"  Client {cid}: {len(cdf)} samples | {cdf['grade'].value_counts().to_dict()}")

    val_loader  = make_loader(splits["val"],  cfg, train=False)
    test_loader = make_loader(splits["test"], cfg, train=False)

    global_model = build_model(cfg)
    global_sd    = get_state_dict_cpu(global_model)
    best_val_f1, best_sd = -1.0, None
    history = []
    scaler = torch.cuda.amp.GradScaler() if cfg.use_amp else None

    for rnd in range(1, rounds + 1):
        client_sds, client_sizes = [], []
        for cid, cdf in client_dfs.items():
            local_model = build_model(cfg)
            load_state_dict_cpu(local_model, global_sd)
            criterion = make_criterion(cdf, cfg)
            optimizer = torch.optim.AdamW(
                local_model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay
            )
            loader   = make_loader(cdf, cfg, train=True, use_sampler=False)
            g_params = [p.detach().cpu() for p in global_model.parameters() if p.requires_grad]
            for _ in range(local_epochs):
                train_one_epoch(local_model, loader, optimizer, criterion,
                                scaler=scaler, global_params=g_params, mu=mu)
            client_sds.append(get_state_dict_cpu(local_model))
            client_sizes.append(len(cdf))
            del local_model

        new_sd    = fedavg_aggregate(client_sds, client_sizes)
        global_sd = blend_sd(global_sd, new_sd, cfg.server_lr)
        load_state_dict_cpu(global_model, global_sd)

        v_metrics = evaluate(global_model, val_loader)
        row = {"round": rnd,
               "val_acc": round(v_metrics["acc"], 4),
               "val_f1":  round(v_metrics["macro_f1"], 4)}
        history.append(row)
        print(f"  Round {rnd:2d}/{rounds}  "
              f"val_acc={v_metrics['acc']:.3f}  val_f1={v_metrics['macro_f1']:.3f}")

        if v_metrics["macro_f1"] > best_val_f1:
            best_val_f1 = v_metrics["macro_f1"]
            best_sd     = copy.deepcopy(global_sd)

    load_state_dict_cpu(global_model, best_sd)
    test_metrics = evaluate(global_model, test_loader)
    print(f"\n  [TEST] acc={test_metrics['acc']:.4f}  "
          f"f1={test_metrics['macro_f1']:.4f}  "
          f"recalls={[round(r,3) for r in test_metrics['recall_per_class']]}")

    pd.DataFrame(history).to_csv(out_dir / "dirichlet_history.csv", index=False)
    save_metrics(test_metrics, out_dir / "dirichlet_test_metrics.csv")
    torch.save(best_sd, out_dir / "dirichlet_best_model.pt")
    plot_confusion_matrix(test_metrics["cm"], CLASS_NAMES,
                          f"FL-Dirichlet Fixed — {branch_name}",
                          out_dir / "dirichlet_confusion_matrix.png")
    plot_convergence(history, f"FL-Dirichlet Fixed — {branch_name}",
                     out_dir / "dirichlet_convergence.png")
    print(f"  Saved outputs to {out_dir}")
    return test_metrics


# ── Run both branches ───────────────────────────────────────
cfg = CFG()
dirichlet_results = []

for keep_4x in [True, False]:
    branch_name = "with_4x" if keep_4x else "without_4x"
    out_dir = OUT_BASE / branch_name / "fl_dirichlet_fixed"

    print(f"\n{'#'*60}")
    print(f"# BRANCH: {branch_name}")
    print(f"{'#'*60}")

    df_all = build_index(DATA_ROOT, keep_4x=keep_4x)
    splits = split_by_image_stratified(df_all, cfg)
    print(f"  train={len(splits['train'])}  val={len(splits['val'])}  test={len(splits['test'])}")

    metrics = run_fl_dirichlet_fixed(
        splits, cfg,
        out_dir      = out_dir,
        branch_name  = branch_name,
        alpha        = 1.0,   # was 0.3 — key fix
        mu           = 0.1,   # was 0.01
        local_epochs = 2,     # was 1
        rounds       = 20,    # was 10
    )

    dirichlet_results.append({
        "branch":       branch_name,
        "experiment":   "FL_Dirichlet_Fixed",
        "alpha":        1.0,
        "mu":           0.1,
        "local_epochs": 2,
        "rounds":       20,
        "acc":          round(metrics["acc"],       4),
        "macro_f1":     round(metrics["macro_f1"],  4),
        "macro_auc":    round(metrics["macro_auc"], 4),
        "R1_Grade_I":   round(metrics["recall_per_class"][0], 4),
        "R2_Grade_II":  round(metrics["recall_per_class"][1], 4),
        "R3_Grade_III": round(metrics["recall_per_class"][2], 4),
        "F1_Grade_I":   round(metrics["f1_per_class"][0], 4),
        "F1_Grade_II":  round(metrics["f1_per_class"][1], 4),
        "F1_Grade_III": round(metrics["f1_per_class"][2], 4),
    })

print("\n" + "="*60)
print("FL-DIRICHLET FIXED — FINAL COMPARISON")
print("="*60)
print(pd.DataFrame(dirichlet_results).to_string(index=False))

# ── Append Dirichlet results to all_results for unified tables/figures ──
all_results.extend([
    {
        "Branch":       row["branch"],
        "Method":       "FL-Dirichlet",
        "Rounds/Epochs": row["rounds"],
        "LR":           CFG_DEFAULT.lr,
        "mu":           row["mu"],
        "Acc":          row["acc"],
        "Macro-F1":     row["macro_f1"],
        "Macro-AUC":    row["macro_auc"],
        "Recall-GI":    row["R1_Grade_I"],
        "Recall-GII":   row["R2_Grade_II"],
        "Recall-GIII":  row["R3_Grade_III"],
        "F1-GI":        row["F1_Grade_I"],
        "F1-GII":       row["F1_Grade_II"],
        "F1-GIII":      row["F1_Grade_III"],
    }
    for row in dirichlet_results
])
print("\nDirichlet results merged into all_results for final tables & figures.")

# ============================================================
# Cell 13 — Results Table
# ============================================================
results_df = pd.DataFrame(all_results)

print("\n" + "="*90)
print("COLON5 — COMPLETE RESULTS TABLE")
print("="*90)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)
pd.set_option('display.float_format', '{:.4f}'.format)
print(results_df.to_string(index=False))

# Save CSV
results_df.to_csv(OUT_BASE / "colon5_all_results.csv", index=False)

# ── LaTeX table — main results ─────────────────────────────
latex_cols = ["Branch", "Method", "Acc", "Macro-F1", "Macro-AUC",
              "Recall-GI", "Recall-GII", "Recall-GIII"]
latex_df = results_df[latex_cols].copy()

# Bold the best value per metric per branch
for branch in ["with_4x", "without_4x"]:
    mask = latex_df["Branch"] == branch
    for col in ["Acc", "Macro-F1", "Macro-AUC"]:
        best_idx = latex_df.loc[mask, col].idxmax()
        latex_df.loc[best_idx, col] = f"\\textbf{{{latex_df.loc[best_idx, col]:.4f}}}"

latex_str = latex_df.to_latex(
    index=False,
    escape=False,
    caption=(
        "Classification performance of Centralized and Federated (FL-IID FedProx) "
        "learning on CRC-HGD-v2. Results reported on the held-out test set "
        "(15\\% stratified split). Bold: best per metric per magnification branch."
    ),
    label="tab:colon5_results",
    column_format="llccccccc",
)
with open(OUT_BASE / "colon5_results_table.tex", "w") as f:
    f.write(latex_str)

# ── LaTeX table — per-class F1 ─────────────────────────────
f1_cols = ["Branch", "Method", "F1-GI", "F1-GII", "F1-GIII", "Macro-F1"]
f1_latex = results_df[f1_cols].to_latex(
    index=False,
    float_format="{:.4f}".format,
    caption="Per-class F1-score breakdown. GI=Grade I (Well Diff.), GII=Grade II (Mod. Diff.), GIII=Grade III (Poorly Diff.).",
    label="tab:colon5_f1_breakdown",
    column_format="llcccc",
)
with open(OUT_BASE / "colon5_f1_table.tex", "w") as f:
    f.write(f1_latex)

print(f"\nSaved: colon5_all_results.csv")
print(f"Saved: colon5_results_table.tex")
print(f"Saved: colon5_f1_table.tex")

# ── Pivot summary ──────────────────────────────────────────
print("\nPivot — Acc & Macro-F1 by Method × Branch:")
pivot = results_df.pivot_table(
    index="Method", columns="Branch",
    values=["Acc", "Macro-F1", "Macro-AUC"]
)
print(pivot.round(4).to_string())

# ============================================================
# Cell 14 — Figure: Method × Branch Comparison (Acc + F1 + AUC)
# ============================================================
methods   = results_df["Method"].unique().tolist()
branches  = ["with_4x", "without_4x"]
metrics   = [("Acc", "Accuracy"), ("Macro-F1", "Macro F1"), ("Macro-AUC", "Macro AUC")]

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
x = np.arange(len(methods))
width = 0.35

for ax, (metric_col, metric_label) in zip(axes, metrics):
    for bi, (branch, color) in enumerate(zip(branches, COLORS)):
        vals = [
            results_df[(results_df["Branch"] == branch) &
                       (results_df["Method"]  == m)][metric_col].values[0]
            for m in methods
        ]
        bars = ax.bar(x + bi * width - width/2, vals, width,
                      label=branch.replace('_', ' '), color=color,
                      edgecolor='white', linewidth=0.8)
        for bar, v in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                    f'{v:.3f}', ha='center', va='bottom', fontsize=8.5)
    ax.set_xticks(x)
    ax.set_xticklabels(methods, rotation=10, ha='right')
    ax.set_ylabel(metric_label)
    ax.set_title(f'{metric_label} Comparison')
    ax.set_ylim(0, 1.12)
    ax.legend()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

fig.suptitle('Centralized vs Federated Learning on CRC-HGD-v2',
             fontsize=13, fontweight='bold')
fig.tight_layout()
fig.savefig(OUT_BASE / 'fig_method_comparison.png')
plt.show()
plt.close(fig)
print("Saved: fig_method_comparison.png")

# ============================================================
# Cell 15 — Figure: Per-Class Recall Heatmap
# ============================================================
recall_cols = ["Recall-GI", "Recall-GII", "Recall-GIII"]
x_labels    = ["Grade I", "Grade II", "Grade III"]

fig, axes = plt.subplots(1, len(methods), figsize=(6 * len(methods), 5), sharey=True)
if len(methods) == 1:
    axes = [axes]

for ax, method in zip(axes, methods):
    sub = results_df[results_df["Method"] == method]
    x = np.arange(len(recall_cols))
    for bi, (branch, color) in enumerate(zip(branches, COLORS)):
        row = sub[sub["Branch"] == branch]
        if len(row) == 0:
            continue
        vals = [row[rc].values[0] for rc in recall_cols]
        bars = ax.bar(x + bi * 0.35 - 0.175, vals, 0.35,
                      label=branch.replace('_', ' '), color=color,
                      edgecolor='white', linewidth=0.8)
        for bar, v in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.008,
                    f'{v:.3f}', ha='center', va='bottom', fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(x_labels, rotation=10, ha='right')
    ax.set_title(method, fontweight='bold')
    ax.set_ylabel('Recall') if ax == axes[0] else None
    ax.set_ylim(0, 1.15)
    ax.legend(fontsize=9)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

fig.suptitle('Per-Class Recall: Centralized vs FL-IID FedProx',
             fontsize=13, fontweight='bold')
fig.tight_layout()
fig.savefig(OUT_BASE / 'fig_per_class_recall.png')
plt.show()
plt.close(fig)
print("Saved: fig_per_class_recall.png")

# ============================================================
# Cell 16 — Figure: Convergence Overlay (both branches)
# ============================================================
def load_history(path: Path):
    if path.exists():
        return pd.read_csv(path)
    return None


fig, axes = plt.subplots(2, 2, figsize=(14, 10))

plot_specs = [
    # (branch,        exp_dir,         file,                   x_col,   label)
    ("with_4x",    "centralized",  "central_history.csv",   "epoch",  "Centralized with_4x"),
    ("without_4x", "centralized",  "central_history.csv",   "epoch",  "Centralized without_4x"),
    ("with_4x",    "fl_iid",       "iid_history.csv",       "round",  "FL-IID with_4x"),
    ("without_4x", "fl_iid",       "iid_history.csv",       "round",  "FL-IID without_4x"),
]
line_styles = ['-', '--', '-.', ':']

ax_loss = axes[0][0]
ax_vacc = axes[0][1]
ax_vf1  = axes[1][0]
ax_vauc = axes[1][1]

for (branch, exp, fname, x_col, label), ls, color in zip(
    plot_specs, line_styles, COLORS
):
    df_h = load_history(OUT_BASE / branch / exp / fname)
    if df_h is None:
        continue
    xs = df_h[x_col]
    kw = dict(linestyle=ls, color=color, linewidth=2, marker='o', markersize=4)
    if "train_loss" in df_h.columns:
        ax_loss.plot(xs, df_h["train_loss"], label=label, **kw)
    if "val_acc" in df_h.columns:
        ax_vacc.plot(xs, df_h["val_acc"],  label=label, **kw)
    if "val_f1" in df_h.columns:
        ax_vf1.plot(xs,  df_h["val_f1"],   label=label, **kw)
    if "val_auc" in df_h.columns:
        ax_vauc.plot(xs, df_h["val_auc"],  label=label, **kw)

for ax, ylabel, title in [
    (ax_loss, "Loss",     "Training Loss"),
    (ax_vacc, "Accuracy", "Validation Accuracy"),
    (ax_vf1,  "F1",       "Validation Macro-F1"),
    (ax_vauc, "AUC",      "Validation Macro-AUC"),
]:
    ax.set_ylabel(ylabel)
    ax.set_title(title, fontweight='bold')
    ax.legend(fontsize=9)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    if ylabel != "Loss":
        ax.set_ylim(0, 1.05)

axes[1][0].set_xlabel('Epoch / Round')
axes[1][1].set_xlabel('Epoch / Round')

fig.suptitle('Training Convergence — All Experiments & Branches',
             fontsize=13, fontweight='bold')
fig.tight_layout()
fig.savefig(OUT_BASE / 'fig_convergence_overlay.png')
plt.show()
plt.close(fig)
print("Saved: fig_convergence_overlay.png")

# ============================================================
# Cell 17 — Figure: Radar / Spider Chart (multi-metric)
# ============================================================
def radar_chart(categories, values_list, labels, title, out_path: Path):
    N = len(categories)
    angles = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()
    angles += angles[:1]  # close the polygon

    fig, ax = plt.subplots(figsize=(7, 7), subplot_kw=dict(polar=True))
    for vals, label, color in zip(values_list, labels, COLORS):
        vals_closed = list(vals) + [vals[0]]
        ax.plot(angles, vals_closed, color=color, linewidth=2, label=label)
        ax.fill(angles, vals_closed, color=color, alpha=0.12)

    ax.set_thetagrids(np.degrees(angles[:-1]), categories, fontsize=10)
    ax.set_ylim(0, 1)
    ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
    ax.set_yticklabels(['0.2','0.4','0.6','0.8','1.0'], fontsize=8)
    ax.set_title(title, fontsize=12, fontweight='bold', pad=20)
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), fontsize=9)
    fig.tight_layout()
    fig.savefig(out_path)
    plt.show()
    plt.close(fig)


radar_categories = ["Accuracy", "Macro-F1", "Macro-AUC",
                    "Recall-GI", "Recall-GII", "Recall-GIII"]
radar_cols       = ["Acc", "Macro-F1", "Macro-AUC",
                    "Recall-GI", "Recall-GII", "Recall-GIII"]

radar_values = []
radar_labels = []
for _, row in results_df.iterrows():
    radar_values.append([row[c] for c in radar_cols])
    radar_labels.append(f"{row['Method']}\n({row['Branch']})")

radar_chart(
    radar_categories, radar_values, radar_labels,
    "Multi-Metric Radar: All Experiments",
    OUT_BASE / "fig_radar_comparison.png"
)
print("Saved: fig_radar_comparison.png")

# ============================================================
# Cell 18 — Figure: Combined Confusion Matrices Panel
# ============================================================
import matplotlib.gridspec as gridspec

def load_cm(branch, exp_dir, fname_prefix):
    """Load test metrics CSV and reconstruct confusion matrix from saved PNG path."""
    # We re-run evaluate to get cm — here we load from saved CSV as proxy
    # (actual cm PNG is already saved per experiment; this cell creates a combined panel)
    png_path = OUT_BASE / branch / exp_dir / f"{fname_prefix}_confusion_matrix.png"
    return png_path

panel_specs = [
    ("with_4x",    "centralized", "central",    "Centralized\nwith 4×"),
    ("without_4x", "centralized", "central",    "Centralized\nwithout 4×"),
    ("with_4x",    "fl_iid",      "iid",        "FL-IID FedProx\nwith 4×"),
    ("without_4x", "fl_iid",      "iid",        "FL-IID FedProx\nwithout 4×"),
]

fig, axes = plt.subplots(2, 2, figsize=(14, 11))
axes = axes.flatten()

for ax, (branch, exp_dir, prefix, title) in zip(axes, panel_specs):
    img_path = OUT_BASE / branch / exp_dir / f"{prefix}_confusion_matrix.png"
    if img_path.exists():
        img = plt.imread(str(img_path))
        ax.imshow(img)
        ax.set_title(title, fontsize=11, fontweight='bold')
    else:
        ax.text(0.5, 0.5, f'Not found:\n{img_path.name}',
                ha='center', va='center', transform=ax.transAxes, fontsize=9)
    ax.axis('off')

fig.suptitle('Confusion Matrices — All Experiments & Branches',
             fontsize=13, fontweight='bold')
fig.tight_layout()
fig.savefig(OUT_BASE / 'fig_confusion_panel.png')
plt.show()
plt.close(fig)
print("Saved: fig_confusion_panel.png")

# ============================================================
# Cell 19 — Publication Summary & Output Index
# ============================================================
print("\n" + "="*70)
print("PUBLICATION OUTPUT INDEX")
print("="*70)

sections = {
    "Tables (LaTeX)": [
        "colon5_results_table.tex   — Main results table (Acc/F1/AUC/Recall)",
        "colon5_f1_table.tex        — Per-class F1 breakdown table",
        "colon5_all_results.csv     — Full results (all metrics)",
    ],
    "Figures": [
        "eda/fig_dataset_statistics.png  — Dataset distribution (EDA)",
        "eda/fig_sample_patches.png      — Representative histopathology samples",
        "fig_method_comparison.png       — Bar chart: Acc/F1/AUC by method & branch",
        "fig_per_class_recall.png        — Per-class recall comparison",
        "fig_convergence_overlay.png     — Training curves (all experiments)",
        "fig_radar_comparison.png        — Radar chart (multi-metric)",
        "fig_confusion_panel.png         — 2×2 confusion matrix panel",
    ],
    "Per-Experiment Outputs": [
        "<branch>/centralized/central_confusion_matrix.png",
        "<branch>/centralized/central_convergence.png",
        "<branch>/centralized/central_test_metrics.csv",
        "<branch>/centralized/central_best_model.pt",
        "<branch>/fl_iid/iid_confusion_matrix.png",
        "<branch>/fl_iid/iid_convergence.png",
        "<branch>/fl_iid/iid_client_dist.png",
        "<branch>/fl_iid/iid_test_metrics.csv",
        "<branch>/fl_iid/iid_best_model.pt",
    ],
}

for section, items in sections.items():
    print(f"\n  {section}:")
    for item in items:
        print(f"    • {item}")

print(f"\n  Output root: {OUT_BASE}")

# ── Final best result summary ──────────────────────────────
print("\n" + "="*70)
print("BEST RESULTS SUMMARY")
print("="*70)
for branch in ["with_4x", "without_4x"]:
    sub = results_df[results_df["Branch"] == branch]
    best = sub.loc[sub["Macro-F1"].idxmax()]
    print(f"  {branch:15s}  Best: {best['Method']:20s}  "
          f"Acc={best['Acc']:.4f}  F1={best['Macro-F1']:.4f}  AUC={best['Macro-AUC']:.4f}")

print("\n complete.")